### PR TITLE
fix: allow more recent `diffusers` versions

### PR DESCRIPTION
**Pull request by iamwavecut**
I dont know why you only want a certain version of diffusers, but this little check lets you use later versions of diffusers.

### CODE REVIEW

**Comment by iamwavecut** [comment]
@horseee plz check

**Comment by VainF** [comment]
Hi @iamwavecut, Thanks for the PR. Will check this ASAP. Our project started more than 4 months ago. So, we just fixed the version for better reproducibility.

**Comment by iamwavecut** [comment]
@VainF thanks for quick response. However, it might not work, let me draft it for a while and I'll update you later.

**Comment by VainF** [comment]
Update:

Hi @iamwavecut, may I ask where can I find the function `pkg_version`. The following snippet works well on my side:
```python
import diffusers
if diffusers.__version__ >= '0.22.0':
    from diffusers.models.normalization import AdaGroupNorm
else:
    from diffusers.models.attention import AdaGroupNorm
```

**Comment by iamwavecut** [comment]
@VainF i've encountered a couple of obstacles trying to apply it to the most recent version of `diffusers`, because of massive overlap of code duplication, so, I investigate the opportunity to not overwrite, but to monkey patch actual forward implementation. 

It comes with a coat of patch complexity, but, I believe, I would finish it soon, will create new PR then. 

Thanks for merging!

**Pull request merged**
